# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

twitter_config: &twitter_config
  twitter_api_key: <%= ENV["TWITTER_API_KEY"] %>
  twitter_api_sectet: <%= ENV["TWITTER_API_SECRET"] %>

development:
  secret_key_base: 3f92575b955fdcf74096f62152120f8b7557a55ca5ca30d69e508eef99ef33be8e5bd758e50c0a4ae44d91be2768af9008189b18ac9eaa5c6dc3bfded8549e35
  <<: *twitter_config

test:
  secret_key_base: 55d198faab64687e085227c394bba265f0618bfe094d086475344362a300aab6294f8039ac65659560b2b49f6eba48693590ad7ef6fd20a5761fac348a20a4d3
  <<: *twitter_config

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
